CREATE DATABASE IF NOT EXISTS diet;
USE diet;

-- Crear tabla Diet primero
CREATE TABLE IF NOT EXISTS Diet (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Description TEXT NOT NULL,
    Type VARCHAR(20) NOT NULL
);

-- Crear tabla Person después
CREATE TABLE IF NOT EXISTS Person (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Height FLOAT NOT NULL,
    Weight FLOAT NOT NULL,
    Age INT NOT NULL,
    DietID INT, -- Clave foránea
    CONSTRAINT FK_Diet FOREIGN KEY (DietID) REFERENCES Diet(ID) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS Food (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Type VARCHAR(20) NOT NULL,
    Calories INT NOT NULL
);
CREATE TABLE IF NOT EXISTS DietFood (
    DietID INT NOT NULL,
    FoodID INT NOT NULL,
    PRIMARY KEY (DietID, FoodID),
    CONSTRAINT FK_DietFood FOREIGN KEY (DietID) REFERENCES Diet(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Food FOREIGN KEY (FoodID) REFERENCES Food(ID) ON DELETE CASCADE
);
